"Enable Client" = true

[Client]
	#Misc client side changes
	"Enable Misc" = true
	#Makes fog less invasive in some contexts
	"Enable Fog" = true
	#Changes to sounds and music. Disabling this feature requires a Minecraft restart.
	"Enable Sounds & Music" = true
	#Changes to light
	"Enable Light" = true

	#Misc client side changes
	[Client.Misc]
		#Multiplies the world border transparency by this value
		#Range: 0.0 ~ 1.0
		"World Border Transparency" = 0.4
		#If true, the world border height is reduced by 4 times.
		"Shorter world border" = true

	#Makes fog less invasive in some contexts
	[Client.Fog]
		#If true you'll be able to see better in lava when with the Fire Resistance Effect.
		"Better visibility in Lava with Fire Resistance Lava" = true
		#If true Nether Fog is no longer limited to 12 chunks.
		"Better Nether Fog" = true
		#Render distance is multiplied by this value in the Nether. Vanilla is 0.5.
		#Range: 0.0 ~ 1.0
		"Nether Fog Ratio" = 0.75

	#Changes to sounds and music. Disabling this feature requires a Minecraft restart.
	[Client."Sounds & Music"]
		#Multiplies the time it takes for music to play by this value (in vanilla, normal music plays each 10 to 20 minutes).
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		"Music delay multiplier" = 0.1

	#Changes to light
	[Client.Light]
		#If true night vision will no longer flash 10 seconds before expiring, instead will slowly fade out 2 seconds before expiring.
		"No Night Vision Flashing" = true

