ServerEvents.recipes(event => {
    event.remove({output: 'minecraft:wooden_hoe'})
    event.remove({output: 'minecraft:wooden_sword'})
    
    event.remove({output: 'minecraft:stone_hoe'})
    event.remove({output: 'minecraft:stone_sword'})

    event.remove({output: 'create_sa:zinc_helmet'})
    event.remove({output: 'create_sa:zinc_chestplate'})
    event.remove({output: 'create_sa:zinc_leggings'})
    event.remove({output: 'create_sa:zinc_boots'})
    event.remove({output: 'create_sa:zinc_pickaxe'})
    event.remove({output: 'create_sa:zinc_shovel'})
    event.remove({output: 'create_sa:zinc_axe'})
    event.remove({output: 'create_sa:zinc_sword'})
    event.remove({output: 'create_sa:zinc_hoe'})

    event.remove({output: 'create_sa:copper_helmet'})
    event.remove({output: 'create_sa:copper_chestplate'})
    event.remove({output: 'create_sa:copper_leggings'})
    event.remove({output: 'create_sa:copper_boots'})
    event.remove({output: 'create_sa:copper_pickaxe'})
    event.remove({output: 'create_sa:copper_shovel'})
    event.remove({output: 'create_sa:copper_axe'})
    event.remove({output: 'create_sa:copper_sword'})
    event.remove({output: 'create_sa:copper_hoe'})

    event.remove({output: 'create_sa:brass_helmet'})
    event.remove({output: 'create_sa:brass_chestplate'})
    event.remove({output: 'create_sa:brass_leggings'})
    event.remove({output: 'create_sa:brass_boots'})
    event.remove({output: 'create_sa:brass_pickaxe'})
    event.remove({output: 'create_sa:brass_shovel'})
    event.remove({output: 'create_sa:brass_axe'})
    event.remove({output: 'create_sa:brass_sword'})
    event.remove({output: 'create_sa:brass_hoe'})

    event.remove({output: 'create_sa:experience_pickaxe'})
    event.remove({output: 'create_sa:experience_shovel'})
    event.remove({output: 'create_sa:experience_axe'})
    event.remove({output: 'create_sa:experience_sword'})
    
    event.remove({output: 'create_sa:blazing_pickaxe'})
    event.remove({output: 'create_sa:blazing_shovel'})
    event.remove({output: 'create_sa:blazing_axe'})
    event.remove({output: 'create_sa:blazing_cleaver'})

    event.remove({output: 'create_sa:rose_quartz_pickaxe'})
    event.remove({output: 'create_sa:rose_quartz_shovel'})
    event.remove({output: 'create_sa:rose_quartz_axe'})
    event.remove({output: 'create_sa:rose_quartz_sword'})
    
    event.remove({output: 'create_sa:slime_helmet'})
    event.remove({output: 'create_sa:slime_boots'})

    event.remove({output: 'create_sa:copper_magnet'})
    event.remove({output: 'create_sa:drone_controller'})
    event.remove({output: 'create_sa:brass_drone_item'})
    event.remove({output: 'create_sa:flamethrower'})
    event.remove({output: 'create_sa:portable_drill'})
    event.remove({output: 'create_sa:grapplin_whisk'})
    event.remove({output: 'create_sa:block_picker'})
    
    event.remove({output: 'create_sa:andesite_jetpack_chestplate'})
    event.remove({output: 'create_sa:copper_jetpack_chestplate'})
    event.remove({output: 'create_sa:brass_jetpack_chestplate'})
    
    event.remove({output: 'create_sa:andesite_exoskeleton_chestplate'})
    event.remove({output: 'create_sa:copper_exoskeleton_chestplate'})
    event.remove({output: 'create_sa:brass_exoskeleton_chestplate'})
    
    event.remove({output: 'create_sa:small_filling_tank'})
    event.remove({output: 'create_sa:medium_filling_tank'})
    event.remove({output: 'create_sa:large_filling_tank'})
    
    event.remove({output: 'create_sa:small_fueling_tank'})
    event.remove({output: 'create_sa:medium_fueling_tank'})
    event.remove({output: 'create_sa:large_fueling_tank'})
})