
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.forbidden_arcanus]
				aurum = true
				nuggety_aurum = true

			[general.types.leaves_type.ecologics]
				coconut = true
				walnut = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

		[general.types.wood_type]

			[general.types.wood_type.ecologics]
				flowering_azalea = true
				azalea = true
				coconut = true
				walnut = true

			[general.types.wood_type.quark]
				azalea = false
				ancient = true
				blossom = true

			[general.types.wood_type.forbidden_arcanus]
				aurum = true
				edelwood = true

	[general.entries]

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

		[general.entries.wood_type]

			[general.entries.wood_type.quark]
				vertical_planks = true
				post = true
				trapped_chest = true
				bookshelf = true
				chest = true
				stripped_post = true
				ladder = true
				hollow_log = true

			[general.entries.wood_type.another_furniture]
				table = true
				flower_box = true
				shelf = true
				drawer = true
				shutter = true
				bench = true
				chair = true

			[general.entries.wood_type.decorative_blocks]
				beam = true
				support = true
				seat = true
				palisade = true

			[general.entries.wood_type.create]
				window = true
				window_pane = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.mcwdoors]
				nether_door = true
				stable_head_door = true
				japanese2_door = true
				tropical_door = true
				barn_glass_door = true
				cottage_door = true
				four_panel_door = true
				western_door = true
				paper_door = true
				bamboo_door = true
				swamp_door = true
				glass_door = true
				beach_door = true
				barn_door = true
				mystic_door = true
				waffle_door = true
				japanese_door = true
				bark_glass_door = true
				classic_door = true
				stable_door = true
				modern_door = true

			[general.entries.wood_type.mcwtrpdoors]
				ranch_trapdoor = true
				classic_trapdoor = true
				bamboo_trapdoor = true
				beach_trapdoor = true
				swamp_trapdoor = true
				barn_trapdoor = true
				four_panel_trapdoor = true
				glass_trapdoor = true
				barred_trapdoor = true
				blossom_trapdoor = true
				tropical_trapdoor = true
				cottage_trapdoor = true
				paper_trapdoor = true
				bark_trapdoor = true
				mystic_trapdoor = true
				barrel_trapdoor = true

