# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
globalTooltip: true
noMicrosoftTelemetry: true
debug:
  tagsTooltip: true
  debugTooltipMsg: false
  tagsTooltipAppendKeybindHint: false
  tagsPerPage: 6
  NBTTooltip: true
suppressExperimentalSettingsWarning: false
